version: '3.8'

services:
  dm-client:
    restart: always
    build: ./dm-client
    ports: 
      - "8080:8080"
    environment:
      - VITE_BACKEND_HOST=127.0.0.1
      - VITE_BACKEND_PORT=8000
      - VITE_API_VERSION=v1
      - VITE_SOCKET_ID=1234
    networks:
      - app-tier

  dm-service:
    restart: always
    build: ./dm-service
    ports: 
      - "8000:8000"
    depends_on: 
      - cassandra
    networks:
      - app-tier

  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - app-tier
      
volumes:
  cassandra_data:
    driver: local

networks:
  app-tier:
    driver: bridge
